### ISSUE TITLE
Receiving undefined method `gsub' for nil:NilClass on Rails 6.0.3

### ISSUE THREAD

**Issue by RailsCod3rFuture** [richardrails/ransack_memory#8]
When I add include Ransack::Concern/before_action :save_and_load_filters to application_controller.rb. I get gsub for nil:NilClass. Do you know why this error is occurring?

**Comment by richardrails** [comment]
do you have github repo with this example please?

**Comment by richardrails** [comment]
Did you do the config of this gem?

**Comment by TvL2386** [comment]
I had the same error after upgrading from rails-5.2 to rails-6.0.3.4.
After trying to reproduce on a clean project I noticed what caused it in my original project.

My config/initializers/ransack_memory.rb was configured like this:
```ruby
RansackMemory::Core.config = {
  param: :q # this means the default Ransack param name for searching. You can change it
}
```

Instead of:
```ruby
RansackMemory::Core.config = {
  param: :q, # this means the default Ransack param name for searching. You can change it
  session_key_format: '%controller_name%_%action_name%_%request_format%' # this means how the key used to store the information to the session will be stored. Currently it interpolates request parameters. You can customize it and use these vars to build a key that fits your needs
}
```

`rm config/initializers/ransack_memory.rb && rails g ransack_memory` solved it!

Kind regards,
tvl2386
